### ISSUE TITLE
Minor typo in normalizing flows slides

### ISSUE THREAD

**Issue by christabella** [kmkolasinski/deep-learning-notes#15]
Thanks for sharing your amazing notes! In `/seminars/2018-10-Normalizing-Flows-NICE-RealNVP-GLOW/2018.10.10_Normalizing_Flows_NICE_RealNVP_GLOW.pdf` page 9, the expression for the normalizing flow has a typo in the numerator of the Jacobian:

![image](https://user-images.githubusercontent.com/2038751/67225092-3fac1200-f43b-11e9-8e34-ae6ec11fa037.png)

`z` should be `f`, as in the original paper by Rezende (2016):

![image](https://user-images.githubusercontent.com/2038751/67225136-55213c00-f43b-11e9-9e92-a3dab51d1d77.png)

**Comment by kmkolasinski** [comment]
Hi, I think this notation is correct, since on the left side you have an explicit definition of `z(i) `:
![image](https://user-images.githubusercontent.com/10145864/67620562-91241a80-f808-11e9-941d-7bfe597c738d.png)
so I can write this expression using f(z(i-1)) or z(i). Writing this using `z` is more compact to me.  
However indeed, the notation between slides changes. This is because sometimes I try to write equations by my self and sometimes I copy things from papers. Since different papers use different notation, this may cause unnecessary confusions. During my seminars I always try to stress this differences.

**Comment by christabella** [comment]
Oh I see, thanks a lot for the explanation! It makes sense :)
